# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Gitops CI

on:
  push:
    branches: [main]

jobs:
  Startup:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        
    - name: Build clean with Maven
      run: mvn -B clean --file pom.xml
  Compile:

    runs-on: ubuntu-latest
    needs: Startup
    name: Cmp

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        
    - name: Build compile with Maven
      run: mvn -B compile --file pom.xml
  UnitTesting:

    runs-on: ubuntu-latest
    needs: Compile
    name: UT
    steps:
    - run: echo should run unit Tests
    - uses: actions/checkout@v1   
    - name: Build test with Maven
      run: mvn -B test --file pom.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      with:
          files: "target/surefire-reports/*.xml"


    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
